version: "3"
services:
  mariadb:
    image: mariadb:latest
    container_name: mdb_json
    ports: 
      - 3306:3306
    volumes:
      - ./data:/docker-entrypoint-initdb.d
    environment: 
      MARIADB_ROOT_PASSWORD: 'Password123!'